Move missing header for libc++ after 1435be18d410
src/Hy3Node.cpp:571:20: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
        std::stringstream buf;
                          ^
/usr/include/c++/v1/iosfwd:134:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^